"""Fit Dirichlet α from reference_recipes_v1.yaml.

Method:
  1. For each style, compute the (tea, milk, fruit, water, coffee, ice) mass
     partition for every recipe.
  2. Average the partitions per style → ᾱ.
  3. Scale by per-style concentration `kappa`: α = κ × ᾱ
     (higher κ → tighter prior; we use kappa=5 by default, which keeps the
     Dirichlet variance modest while still concentrating around the mean).
  4. Clip to a small positive floor so no role gets zeroed out (preserves
     exploration in the generator).
  5. Write to data/priors/dirichlet_alpha_v2.yaml + writes a side-by-side
     comparison vs the v1 placeholder for sanity.

Usage:
    python scripts/fit_dirichlet_priors.py
    python scripts/fit_dirichlet_priors.py --kappa 8.0 --floor 0.1
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
import typer
import yaml

from beverage_ai.priors.dirichlet import ROLE_ORDER, partition_of_recipe
from beverage_ai.recipes.schema import Recipe

app = typer.Typer(add_completion=False)


@app.command()
def main(
    recipes_path: Path = typer.Option(Path("data/recipes/reference_recipes_v1.yaml")),
    out_path: Path = typer.Option(Path("data/priors/dirichlet_alpha_v2.yaml")),
    v1_path: Path = typer.Option(Path("data/priors/dirichlet_alpha_v1.yaml")),
    kappa: float = typer.Option(5.0, help="Concentration multiplier (higher = tighter)"),
    floor: float = typer.Option(0.05, help="Minimum α value per role"),
    min_recipes_per_style: int = typer.Option(
        5, help="Styles with fewer recipes fall back to v1 prior"
    ),
):
    if not recipes_path.exists():
        typer.echo(f"ERROR: {recipes_path} not found", err=True)
        raise typer.Exit(1)

    with open(recipes_path, encoding="utf-8") as f:
        raw = yaml.safe_load(f) or []
    typer.echo(f"loaded {len(raw)} recipes from {recipes_path}")

    # Group partitions by style
    partitions_by_style: dict[str, list[np.ndarray]] = defaultdict(list)
    for item in raw:
        try:
            r = Recipe(**item)
        except Exception as e:
            typer.echo(f"skip {item.get('recipe_id')}: {e}", err=True)
            continue
        p = partition_of_recipe(r)
        partitions_by_style[r.style].append(p)

    # Load v1 placeholder for fallback + comparison
    with open(v1_path, encoding="utf-8") as f:
        v1 = yaml.safe_load(f) or {}

    new_alpha: dict[str, list[float]] = {}
    typer.echo(f"\nFitting α (κ={kappa}, floor={floor})\n")
    typer.echo(f"{'style':<12s} {'n':>4s}  {'roles → α (rounded)':<50s}  {'vs v1'}")
    typer.echo("-" * 100)

    for style in v1.keys():
        parts = partitions_by_style.get(style, [])
        if len(parts) < min_recipes_per_style:
            new_alpha[style] = list(v1[style])
            typer.echo(
                f"{style:<12s} {len(parts):>4d}  "
                f"<too few recipes, kept v1: {[round(x, 2) for x in v1[style]]}>"
            )
            continue
        mean_partition = np.stack(parts).mean(axis=0)
        alpha = np.clip(kappa * mean_partition, floor, None)
        new_alpha[style] = [round(float(x), 3) for x in alpha]
        delta = np.array(new_alpha[style]) - np.array(v1[style])
        delta_str = "  ".join(f"{r}{'+' if d >= 0 else ''}{d:.2f}"
                              for r, d in zip(ROLE_ORDER, delta, strict=True))
        typer.echo(
            f"{style:<12s} {len(parts):>4d}  "
            f"{str(new_alpha[style]):<50s}  {delta_str}"
        )

    # Write out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header_comment = (
        f"# Dirichlet α fitted from {recipes_path.name}\n"
        f"# Method: per-style mean partition × κ={kappa}, floor={floor}\n"
        f"# Roles order: {list(ROLE_ORDER)}\n"
        f"# Generated by scripts/fit_dirichlet_priors.py\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header_comment)
        yaml.safe_dump(new_alpha, f, allow_unicode=True, sort_keys=False, default_flow_style=True)
    typer.echo(f"\nwrote {out_path}")


if __name__ == "__main__":
    sys.exit(app() or 0)
